### ISSUE TITLE
Rename / redirect

### ISSUE THREAD

**Issue by oscarotero** [middlewares/ideas#17]
A middleware to change the urls of the page using 301 redirects, to be SEO friendly.
More info: https://support.google.com/webmasters/answer/93633?hl=en

**Comment by WyriHaximus** [comment]
Picking this up after our chat on twitter: https://twitter.com/misteroom/status/909345997524004864

**Comment by WyriHaximus** [comment]
Repository is up at https://github.com/wyrihaximus/redirect haven't done the readme though

**Comment by oscarotero** [comment]
Great!
I've created an issue with some suggestions: https://github.com/WyriHaximus/redirect/issues/1

**Comment by WyriHaximus** [comment]
Nice! Will get to those soon 👍
