### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by oscarotero** [middlewares/ideas#19]
A middleware to process incoming and outgoing cookies that can provide some functionalities:

* Add automatically some flags like:
  * `SameSite` [more info](https://scotthelme.co.uk/csrf-is-dead/)
  * `httponly`, `secure`, etc
* Encrypt/decrypt values
* etc.

**Comment by ncou** [comment]
Why open a new issue ? it's not a duplicate with : https://github.com/middlewares/ideas/issues/13
?

**Comment by oscarotero** [comment]
Yes, you're right. I close this.
