### ISSUE TITLE
Mobile_Detect

### ISSUE THREAD

**Issue by mimmi20** [middlewares/ideas#21]
For the PSR-7-middlewares there exist a Middleware which uses Mobile_Detect. This middleware is missing for PSR-15.

**Comment by oscarotero** [comment]
Yes, you're right.
I'll do it when the PSR-15 is released stable (almost there)

**Comment by higoka** [comment]
This is my approach. I basically converted the old PSR-7 to the new PSR-15.
Maybe you can add it to your collection @oscarotero 

https://github.com/higoka/detect-device

**Comment by oscarotero** [comment]
@higoka Thanks for your contribution.
Do you like to transfer your repository to middlewares collection?

**Comment by higoka** [comment]
Sure
