### ISSUE TITLE
Home for relay/middleware ResponseSender ?

### ISSUE THREAD

**Issue by pmjones** [middlewares/ideas#22]
The small list of middleware at relay/middleware is mostly obviated by the AwesomeMiddlewares list. However, the ResponseSender appears to have no corollary. <https://github.com/relayphp/Relay.Middleware/blob/1.x/src/ResponseSender.php>

Would you be interested in me converting it to PSR-15 and contributing for maintenance here? Then I can retire relay/middleware entirely.

If not, no big deal. Thanks for providing this resource.

**Comment by oscarotero** [comment]
Hi, @pmjones 
Absolutelly, you're welcome.
You can create a `middleware/response-sender` package using [this template](https://github.com/middlewares/skeleton) and then join to this organization.

**Comment by pmjones** [comment]
Understood; thanks!

**Comment by oscarotero** [comment]
I just created a middleware with this purpose: https://github.com/middlewares/emitter
