### ISSUE TITLE
PSR-15 compatible validation

### ISSUE THREAD

**Issue by MassiAtZend** [middlewares/ideas#23]
I would like to see a module that allows pre-handler validation based on the name of the route and the method of the HTTP request.

For me the best option would be loading 'input_filter_specs' from a configuration referencing the route name and the HTTP method (something like ['login' => ['POST' => <specsid1>], 'rottax' => ['GET' => <specs2>]]).

Thanks for the incredible work you're doing.

Best regards,
Massi.

**Comment by oscarotero** [comment]
Hi, @MassiAtZend 
I don't understand. What is the purpose of that middleware? The validation of a route with a http method is achieve with a router like fast-router or aura-router

**Comment by MassiAtZend** [comment]
Hello Oscar, my bad for not explaining myself properly.
The validation MW should validate the data inputs from the user.
Data inputs should be read from attributes, query and content (at least).
There is a non PSR-15 compliant module 'https://github.com/mvlabs/ze-content-validation' that does that. I would like to see a similar one fully PSR-15 compliant.

**Comment by ncou** [comment]
Since the 3 May the Zend Middleware has been updated for PSR15.
I think you can close this ticket.

**Comment by MassiAtZend** [comment]
Thanks for being there.
Regards,
M.
