### ISSUE TITLE
Middleware at the route level

### ISSUE THREAD

**Issue by mav2287** [middlewares/ideas#29]
More so than an idea I have a question on what the best approach is to handling middleware that needs to run for specific routes. For example I have some routes that a user needs to be logged in to access or they should be redirected to a login page. I also have checks for permissions and other items that could be ran as middleware for a specific route. Ideally I would like to define those items as part of the route definition. One of the ways I found to do this is have a dispatcher with the desired middlewares and a callable at the end of the middleware stack. Here is an example of what I mean:

```php
  $r->addRoute(['GET', 'OPTIONS'], '/user/edit',
        new Dispatcher([
            // handler to redirect to login page if not logged in
            (new isNotLoggedInRedirectHandler),
            // handler to show access denied if user doesn't have permission
            (new PermissionsHandler)
                ->hasPermission(['editUser'),
            // code for the actual edit user page
            new CallableHandler( 'HandlerOnceTheseSpecificChecksHaveRun' )
        ])
    );
```

Although this approach does work I just wanted to see if this was an acceptable solution? Is there a "better" way to solve this issue?

**Comment by oscarotero** [comment]
I think it depends of your needs.

In my case I use [middleland](https://github.com/oscarotero/middleland), a PSR-15 dispatcher that allows to set middlewares to only some paths.

But if you need a more powerful tool, maybe [League/Route](https://route.thephpleague.com/5.x/) can help you.

**Comment by mav2287** [comment]
I will take a look at those and see if it is a better fit. The approach I outlined does work. I just wanted to make sure I wasn't creating problems for myself down the road.

I also noticed thought that if you use this approach and have the set the attribute method for FastRoute the request handle throws an error. ```( new Middlewares\FastRoute( $GLOBALS['router'] ) )->attribute('_routeHandler')``` is all it takes to cause this error and you get a RuntimeException on line 72 of ```/middlewares/request-handler/src/RequestHandler.php``` that says``Empty request handler``. 

If you don't have the attribute method set the code runs just fine, but as soon as you set the attribute method this error appears.

**Comment by oscarotero** [comment]
You have to set the new attribute name to requestHandler middleware

**Comment by mav2287** [comment]
Thanks! That solved the issue, however it looks like there is a typo in the https://github.com/middlewares/fast-route Readme.
``` (new Middlewares\RequestHandler())->attribute('route')```
should be
```(new Middlewares\RequestHandler())->handlerAttribute('route')```
I only now figured that out because that is what I was going off and when I tried setting attribute for the request handler it complained that attribute wasn't a method.

**Comment by oscarotero** [comment]
Ah, good catch.
It's already fixed. thanks!
