### ISSUE TITLE
Remove X-Powered-By Header

### ISSUE THREAD

**Issue by mav2287** [middlewares/ideas#31]
There are instances where I don't want the 'X-Powered-By' header in my responses. Removing them can be a bit pesky though because PHP drops them into the response. To deal with it I put together a simple middleware that removes them. Not sure if it should have a repo, but I find it useful. See below:

```
<?php

declare(strict_types=1);

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class RemovePoweredByHeader implements MiddlewareInterface {

    /**
     * Process a server request and return a response.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface {
       $response = $handler->handle($request);

       if (ini_get('expose_php')) {
              // prevent php from inserting a X-Powered-By header
              header_remove('X-Powered-By');
        }
        // remove the X-Powered-By header from the response
        return $response->withoutHeader('X-Powered-By');
        return $response;
    }
}
```

**Comment by oscarotero** [comment]
I don't think this is a good reason to make a middleware. This is a PHP configuration that must be removed globally, and middlewares works only in a concrete scope (a request/response instance).
If you want to disable it, just add a `ini_set('expose_php', 0);` at the begining of your php project.

**Comment by mav2287** [comment]
No need to re-open but just want to leave a note on this as to why I made the middleware in case someone else runs into this issue. There are some configurations where `ini_set('expose_php', 0);` will not work to disable the "X-Powered-By" header , but the above middleware will. I created this to account for that and allow removal in all situations.
